import React from 'react';
import { AlertTriangle, ShieldCheck, HeartPulse } from 'lucide-react';
import { Link } from 'react-router-dom';
import { LangCode } from '../types';
import { useLang } from '../utils/lang';

const T = {
  en: {
    title: 'Medical Disclaimer',
    updated: 'Last updated: June 2026',
    sections: [
      {
        icon: 'alert',
        heading: 'For Informational and Decision-Support Purposes Only',
        body: 'CareCalculus provides clinical calculators, scoring tools, and medical conversion utilities strictly as decision-support aids. The results produced by these tools are intended to assist trained healthcare professionals in their clinical reasoning — they do not constitute medical advice, diagnosis, or treatment recommendations.',
      },
      {
        icon: 'shield',
        heading: 'Not a Substitute for Professional Judgment',
        body: 'No calculator or scoring algorithm can replace a thorough clinical assessment by a qualified and licensed medical professional. Patient outcomes depend on a full evaluation of signs, symptoms, history, laboratory results, imaging, and clinical context that no automated tool can replicate. Always apply your clinical judgment and consult current institutional protocols.',
      },
      {
        icon: 'alert',
        heading: 'Formula Accuracy and Guideline Currency',
        body: 'All formulas implemented on CareCalculus are derived from published peer-reviewed guidelines at the time of implementation. Medical guidelines are updated periodically. Users are responsible for verifying that any formula, scoring system, or reference range remains current with the latest evidence and their institutional standards before clinical application.',
      },
      {
        icon: 'shield',
        heading: 'No Liability',
        body: 'CareCalculus, its developers, and contributors accept no liability for clinical decisions made using results generated by this platform. Use of this site constitutes acceptance of full personal and professional responsibility for how results are interpreted and applied in a clinical setting.',
      },
      {
        icon: 'alert',
        heading: 'Emergency Situations',
        body: 'In life-threatening emergencies, do not rely solely on any web-based calculator. Call emergency services immediately and follow your institutional resuscitation protocols.',
      },
      {
        icon: 'shield',
        heading: 'Pediatric and Special Populations',
        body: 'Some calculators on this platform are validated for adult populations only. Specific pediatric, obstetric, or geriatric reference ranges may differ significantly. Always verify applicability to your patient population before use.',
      },
    ],
  },
  fr: {
    title: 'Avertissement médical',
    updated: 'Dernière mise à jour : juin 2026',
    sections: [
      {
        icon: 'alert',
        heading: 'À des fins d\'information et d\'aide à la décision uniquement',
        body: 'CareCalculus fournit des calculateurs cliniques, des outils de scoring et des convertisseurs médicaux strictement comme aides à la décision. Les résultats produits par ces outils visent à aider les professionnels de santé formés dans leur raisonnement clinique — ils ne constituent pas un avis médical, un diagnostic ou des recommandations de traitement.',
      },
      {
        icon: 'shield',
        heading: 'Ne remplace pas le jugement professionnel',
        body: 'Aucun calculateur ou algorithme de scoring ne peut remplacer une évaluation clinique complète par un professionnel de santé qualifié et habilité. Les résultats pour les patients dépendent d\'une évaluation complète des signes, symptômes, antécédents, examens biologiques, imagerie et contexte clinique qu\'aucun outil automatisé ne peut reproduire.',
      },
      {
        icon: 'alert',
        heading: 'Précision des formules et actualité des recommandations',
        body: 'Toutes les formules implémentées sur CareCalculus sont issues de recommandations publiées au moment de leur mise en œuvre. Les recommandations médicales sont mises à jour périodiquement. Les utilisateurs sont responsables de vérifier l\'actualité de toute formule avant application clinique.',
      },
      {
        icon: 'shield',
        heading: 'Aucune responsabilité',
        body: 'CareCalculus, ses développeurs et contributeurs n\'assument aucune responsabilité pour les décisions cliniques prises à partir des résultats générés par cette plateforme. L\'utilisation de ce site implique l\'acceptation d\'une pleine responsabilité personnelle et professionnelle quant à l\'interprétation et à l\'application des résultats.',
      },
      {
        icon: 'alert',
        heading: 'Situations d\'urgence',
        body: 'En cas d\'urgence vitale, ne vous fiez pas uniquement à un calculateur en ligne. Appelez immédiatement les services d\'urgence et suivez vos protocoles institutionnels de réanimation.',
      },
      {
        icon: 'shield',
        heading: 'Populations pédiatriques et spéciales',
        body: 'Certains calculateurs de cette plateforme ne sont validés que pour les adultes. Les valeurs de référence pédiatriques, obstétricales ou gériatriques peuvent différer significativement. Vérifiez toujours l\'applicabilité à votre population de patients avant utilisation.',
      },
    ],
  },
  
};

export default function Disclaimer({ lang }: { lang: LangCode }) {
  const { langPath } = useLang();
  const t = T[lang];
  const isRtl = false;

  return (
    <div className="space-y-8 pb-8 max-w-3xl mx-auto" dir={isRtl ? 'rtl' : 'ltr'}>
      <div>
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2.5 bg-amber-100 rounded-xl">
            <AlertTriangle className="w-6 h-6 text-amber-600" />
          </div>
          <h1 className="text-2xl font-black text-gray-900 tracking-tight">{t.title}</h1>
        </div>
        <p className="text-xs text-gray-400 font-mono ml-1">{t.updated}</p>
      </div>

      <div className="space-y-4">
        {t.sections.map((section, i) => (
          <section key={i} className="bg-white border border-gray-100 rounded-2xl p-6 space-y-2">
            <h2 className="text-sm font-black text-gray-900 flex items-center gap-2">
              {section.icon === 'alert'
                ? <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0" />
                : <ShieldCheck className="w-4 h-4 text-blue-500 shrink-0" />}
              {section.heading}
            </h2>
            <p className="text-sm text-gray-600 leading-relaxed">{section.body}</p>
          </section>
        ))}
      </div>

      <div className="bg-slate-50 border border-slate-200 rounded-2xl p-5 flex items-start gap-3">
        <HeartPulse className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
        <p className="text-xs text-gray-500 leading-relaxed">
          {lang === 'fr'
            ? 'En utilisant CareCalculus, vous acceptez les termes de cet avertissement. Pour en savoir plus sur notre plateforme, consultez notre '
            : 'By using CareCalculus you agree to the terms of this disclaimer. To learn more about our platform, see our '}
          <Link to={langPath('/about')} className="underline text-blue-600 font-semibold hover:text-blue-800">
            {lang === 'fr' ? 'page À propos' : 'About page'}
          </Link>.
        </p>
      </div>
    </div>
  );
}
